THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "tr3L10B32MB.py", line 148, in <module>
    model.cuda()
  File "/home/alumnos/alumno1/software/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 307, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/alumnos/alumno1/software/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/alumnos/alumno1/software/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 144, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home/alumnos/alumno1/software/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/home/alumnos/alumno1/software/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 307, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/alumnos/alumno1/software/miniconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/THC/THCGeneral.cpp:47
